"""add reports table

Revision ID: 8e322c6e38bb
Revises: 6350033965fa
Create Date: 2025-05-04 15:01:46.312686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e322c6e38bb'
down_revision: Union[str, None] = '6350033965fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('report_content_markdown', sa.Text(), nullable=False),
    sa.Column('report_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model_used', sa.String(length=128), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.trigger_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('trigger_id')
    )
    op.create_index('idx_reports_asset_id_created_at', 'reports', ['asset_id', 'created_at'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_asset_id_created_at', table_name='reports', postgresql_using='btree')
    op.drop_table('reports')
    # ### end Alembic commands ###
