"""initial schema

Revision ID: d602b547996a
Revises: 
Create Date: 2025-04-07 13:31:02.937483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd602b547996a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('coingecko_id', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('coingecko_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_assets_category', 'assets', ['category'], unique=False)
    op.create_index('idx_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_table('triggers',
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_index('idx_triggers_asset_id_created_at', 'triggers', ['asset_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_triggers_status', 'triggers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_triggers_status', table_name='triggers')
    op.drop_index('idx_triggers_asset_id_created_at', table_name='triggers', postgresql_using='btree')
    op.drop_table('triggers')
    op.drop_index('idx_assets_symbol', table_name='assets')
    op.drop_index('idx_assets_category', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
