agent_name: dyor_agent
author: xiuxiuxar
version: 0.1.0
license: Apache-2.0
description: DYOR Agent is a specialized autonomous research agent that generates
  timely and concise research reports for crypto assets, leveraging Trendmoon APIs
  and associated data sources.
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeiao4wbbcqq73426vpdh6tpucwgwq2n6wczr3xgyebt2e22cpvwkwm
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiaz5auftwxpt4czrmeeesggqlkc2kosmetq6adrebeu6g7bkhqc2u
- eightballer/http_server:0.1.0:bafybeidrvllrr23mc6bvjxn6v3hny6oiwhfgi72n2b7w6ck5luousjfbbq
- eightballer/prometheus:0.1.1:bafybeicy4ck2wvauo2vh6ji64xrzlgezh27powi6ztokr4yujtf3cft6wi
- eightballer/websocket_server:0.1.0:bafybeic3mpzkth76cx5in6hzxtqxelzvrdbzzxhe4n7kt4zyzqsgklyy4m
contracts: []
protocols:
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
- eightballer/websockets:0.1.0:bafybeihdxrqup26ss4jsszcinurilys5bsvzuijwb75vdk7wsh6aeztz34
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
skills:
- eightballer/prometheus:0.1.0:bafybeicl5i7e467aowfarke4bbyixo2dggar276njmvyuwbsby5pxshhtu
- xiuxiuxar/dyor_app:0.1.0:bafybeicnggatr5yftefrcvzcntvszmoz6kbggih6ykmvp3zzdguaygpfyu
customs:
- xiuxiuxar/dyor_api:0.1.0:bafybeic2ngukvyual4mrwm4rp2zbqnzbn3op2p3e22e4si3kuwp4vee4je
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
---
public_id: eightballer/prometheus:0.1.1:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
type: connection
config:
  host: 0.0.0.0
  port: 8716
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: xiuxiuxar/dyor_app:0.1.0
---
public_id: eightballer/websocket_server:0.1.0:bafybeib4t4ay6kfjokq3cydparpzs4zllyl2yujvfsbc24xogwyxsswaqy
type: connection
config:
  host: 0.0.0.0
  port: 5556
  target_skill_id: xiuxiuxar/dyor_app:0.1.0
---
public_id: xiuxiuxar/dyor_app:0.1.0
type: skill
behaviours:
  main:
    args:
      max_workers: ${SKILL_DYOR_APP_BEHAVIOURS_MAIN_ARGS_MAX_WORKERS:int:4}
      api_name: ${SKILL_DYOR_APP_BEHAVIOURS_MAIN_ARGS_API_NAME:str:xiuxiuxar/dyor_api}
      ntfy_topic: ${SKILL_DYOR_APP_BEHAVIOURS_MAIN_ARGS_NTFY_TOPIC:str:alerts}
handlers:
  metrics_handler:
    args:
      enable_cors: false
      expected_api_key: ${SKILL_DYOR_APP_HANDLERS_METRICS_HANDLER_ARGS_EXPECTED_API_KEY:str:key}
models:
  db_model:
    args:
      POSTGRES_USER: ${SKILL_DYOR_APP_MODELS_DB_MODEL_ARGS_POSTGRES_USER:str:user}
      POSTGRES_PASSWORD: ${SKILL_DYOR_APP_MODELS_DB_MODEL_ARGS_POSTGRES_PASSWORD:str:pass}
      POSTGRES_HOST: ${SKILL_DYOR_APP_MODELS_DB_MODEL_ARGS_POSTGRES_HOST:str:host.docker.internal}
      POSTGRES_PORT: ${SKILL_DYOR_APP_MODELS_DB_MODEL_ARGS_POSTGRES_PORT:int:5432}
      POSTGRES_DB: ${SKILL_DYOR_APP_MODELS_DB_MODEL_ARGS_POSTGRES_DB:str:db_name}
  llm_service:
    args:
      LLM_PRIMARY_MODEL: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_PRIMARY_MODEL:str:Meta-Llama-3-3-70B-Instruct}
      LLM_FALLBACK_MODEL: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_FALLBACK_MODEL:str:DeepSeek-R1-Distill-Qwen-32B}
      LLM_API_KEY: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_API_KEY:str:key}
      LLM_BASE_URL: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_BASE_URL:str:https://api.openai.com/v1}
      LLM_MAX_RETRIES: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_MAX_RETRIES:int:4}
      LLM_BACKOFF_FACTOR: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_BACKOFF_FACTOR:float:1.5}
      LLM_TIMEOUT: ${SKILL_DYOR_APP_MODELS_LLM_SERVICE_ARGS_LLM_TIMEOUT:int:60}
  lookonchain_client:
    args:
      base_url: ${SKILL_DYOR_APP_MODELS_LOOKONCHAIN_CLIENT_ARGS_BASE_URL:str:http://localhost:8000}
      search_endpoint: ${SKILL_DYOR_APP_MODELS_LOOKONCHAIN_CLIENT_ARGS_SEARCH_ENDPOINT:str:http://localhost:8000}
      timeout: ${SKILL_DYOR_APP_MODELS_LOOKONCHAIN_CLIENT_ARGS_TIMEOUT:int:15}
      max_retries: ${SKILL_DYOR_APP_MODELS_LOOKONCHAIN_CLIENT_ARGS_MAX_RETRIES:int:3}
      backoff_factor: ${SKILL_DYOR_APP_MODELS_LOOKONCHAIN_CLIENT_ARGS_BACKOFF_FACTOR:float:0.5}
  researchagent_client:
    args:
      base_url: ${SKILL_DYOR_APP_MODELS_RESEARCHAGENT_CLIENT_ARGS_BASE_URL:str:http://localhost:8000}
      api_key: ${SKILL_DYOR_APP_MODELS_RESEARCHAGENT_CLIENT_ARGS_API_KEY:str:key}
  treeofalpha_client:
    args:
      base_url: ${SKILL_DYOR_APP_MODELS_TREEOFALPHA_CLIENT_ARGS_BASE_URL:str:http://localhost:8000}
      news_endpoint: ${SKILL_DYOR_APP_MODELS_TREEOFALPHA_CLIENT_ARGS_NEWS_ENDPOINT:str:news}
      cache_ttl: ${SKILL_DYOR_APP_MODELS_TREEOFALPHA_CLIENT_ARGS_CACHE_TTL:int:3600}
      max_retries: ${SKILL_DYOR_APP_MODELS_TREEOFALPHA_CLIENT_ARGS_MAX_RETRIES:int:3}
      backoff_factor: ${SKILL_DYOR_APP_MODELS_TREEOFALPHA_CLIENT_ARGS_BACKOFF_FACTOR:float:0.5}
  trendmoon_client:
    args:
      base_url: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_BASE_URL:str:http://localhost:8000}
      insights_url: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_INSIGHTS_URL:str:http://localhost:8000/insights}
      api_key: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_API_KEY:str:key}
      max_retries: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_MAX_RETRIES:int:3}
      backoff_factor: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_BACKOFF_FACTOR:float:0.5}
      timeout: ${SKILL_DYOR_APP_MODELS_TRENDMOON_CLIENT_ARGS_TIMEOUT:int:15}
  unlocks_client:
    args:
      base_url: ${SKILL_DYOR_APP_MODELS_UNLOCKS_CLIENT_ARGS_BASE_URL:str:http://localhost:8000}
      timeout: ${SKILL_DYOR_APP_MODELS_UNLOCKS_CLIENT_ARGS_TIMEOUT:int:15}
      max_retries: ${SKILL_DYOR_APP_MODELS_UNLOCKS_CLIENT_ARGS_MAX_RETRIES:int:3}
      backoff_factor: ${SKILL_DYOR_APP_MODELS_UNLOCKS_CLIENT_ARGS_BACKOFF_FACTOR:float:0.5}
