agent_name: dyor_agent
author: xiuxiuxar
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeiao4wbbcqq73426vpdh6tpucwgwq2n6wczr3xgyebt2e22cpvwkwm
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiaz5auftwxpt4czrmeeesggqlkc2kosmetq6adrebeu6g7bkhqc2u
- eightballer/http_server:0.1.0:bafybeidrvllrr23mc6bvjxn6v3hny6oiwhfgi72n2b7w6ck5luousjfbbq
- eightballer/prometheus:0.1.1:bafybeicy4ck2wvauo2vh6ji64xrzlgezh27powi6ztokr4yujtf3cft6wi
contracts: []
protocols:
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
skills:
- eightballer/prometheus:0.1.0:bafybeicl5i7e467aowfarke4bbyixo2dggar276njmvyuwbsby5pxshhtu
- xiuxiuxar/simple_fsm:0.1.0:bafybeibdnbli6h2wuk463lmewti5n26ikozwqf72lx6d74qt3wlhfersry
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: xiuxiuxar/simple_fsm:0.1.0
---
public_id: xiuxiuxar/simple_fsm:0.1.0
type: skill
handlers:
  metrics_handler:
    args:
      enable_cors: false
      expected_api_key: ${str:key}
models:
  db_model:
    args:
      POSTGRES_USER: ${str:user}
      POSTGRES_PASSWORD: ${str:password}
      POSTGRES_HOST: ${str:localhost}
      POSTGRES_PORT: ${int:1}
      POSTGRES_DB: ${str:db_name}
