# This is a basic workflow to help you get started with Actions

name: Code Quality
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        # - "3.9"
        - "3.11"
        poetry-version: ["1.8.3"]
        os: [ubuntu-24.04,]
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: .
      PYTHONWARNINGS: ignore
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install Project
        run: |
            make install

      - name: Format
        run: |
            make fmt

      - name: Lint
        run: |
            make lint

      - name: Tests
        run: |
            make test
        env:
          CI: "true"
          LOOKONCHAIN_BASE_URL: ${{ secrets.LOOKONCHAIN_BASE_URL }}
          LOOKONCHAIN_SEARCH_ENDPOINT: ${{ secrets.LOOKONCHAIN_SEARCH_ENDPOINT }}
          TREE_OF_ALPHA_BASE_URL: ${{ secrets.TREE_OF_ALPHA_BASE_URL }}
          TREE_OF_ALPHA_NEWS_ENDPOINT: ${{ secrets.TREE_OF_ALPHA_NEWS_ENDPOINT }}
          TREE_OF_ALPHA_CACHE_TTL: 300
          TRENDMOON_INSIGHTS_URL: ${{ secrets.TRENDMOON_INSIGHTS_URL }}
          TRENDMOON_STAGING_API_KEY: ${{ secrets.TRENDMOON_STAGING_API_KEY }}
          TRENDMOON_STAGING_URL: ${{ secrets.TRENDMOON_STAGING_URL }}